#!/bin/sh

combine  -M AsymptoticLimits -v 3 --cminDefaultMinimizerStrategy 0 --rAbsAcc 0.001 --X-rtd FITTER_NEW_CROSSING_ALGO --X-rtd FITTER_NEVER_GIVE_UP --X-rtd FITTER_BOUND --cminDefaultMinimizerTolerance=1.0 --run blind --rMin 0.0 --rMax 20.0 -m 800 -n blinded_m800 -d ./combine_datacard_hplushadronic_m800.txt
